### PR TITLE
Duration colorization

### PR DESCRIPTION
**Pull request by bahadasx**
Addresses #35 - Created a property in models.py for Log model to pass color based on duration. If finished is present, then there is no color returned in the property. This property is called within the status.html page in the "Duration" cell.

### CODE REVIEW

**Comment by bahadasx** [comment]
I didn't mean to make the last PR for master.  It was late!

**Comment by bbengfort** [comment]
@bahadasx no problem - don't worry!

**Comment by bbengfort** [comment]
I have to say - pull requests make more sense to me on the command line then they do in the web application!

**Comment by bbengfort** [comment]
Oh - and you should do a pull from develop since I had to resolve a minor merge conflict.

**Pull request merged**
